### Project specific config ###
language: node_js
node_js: lts/*
os: osx

env:
  matrix:
    - ATOM_CHANNEL=stable
    - ATOM_CHANNEL=beta

before_install:
  - brew update
  - brew outdated swiftlint || brew upgrade swiftlint

### Generic setup follows ###
install:
  - curl -s -O https://raw.githubusercontent.com/atom/ci/master/build-package.sh
  - chmod u+x build-package.sh
  - "./build-package.sh"

script:
  - commitlint-travis

after_success:
  - bash <(curl -s https://codecov.io/bash)

branches:
  only:
    - master
    - "/^greenkeeper/.*$/"

git:
  depth: 10

stages:
  - test
  - name: release
    if: (NOT type = pull_request) AND branch = master

jobs:
  include:
    - stage: release
      node_js: lts/*
      script:
        - export PATH=${PATH}:./atom/Atom.app/Contents/Resources/app/apm/node_modules/.bin/
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
