language: objective-c

notifications:
  email:
    on_success: never
    on_failure: change

install: brew update && brew install swiftlint
script: 'curl -s https://raw.githubusercontent.com/atom/ci/master/build-package.sh | sh'
