### Project specific config ###
language: objective-c
osx_image: xcode8.2

env:
  matrix:
    - ATOM_CHANNEL=stable
    - ATOM_CHANNEL=beta

install:
  - brew update
  - brew outdated swiftlint || brew upgrade swiftlint

### Generic setup follows ###
script:
  - curl -s -O https://raw.githubusercontent.com/atom/ci/master/build-package.sh
  - chmod u+x build-package.sh
  - ./build-package.sh

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

git:
  depth: 10
